import type { Metadata } from "next";
import "../globals.css";
import { Inter } from "next/font/google";
import Navbar from "../_components/Navbar";
import CompanyLogos from "../_components/CompanyLogos";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FlyHigher - Website Booking Ticket",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} text-white bg-flysha-black  antialiased font-poppins `}
      >
        <section
          id="Signup"
          className="bg-[url('/assets/images/background/airplane.png')] bg-no-repeat bg-cover bg-left-top -z-10 min-h-screen"
        >
          <div className="Header-content bg-gradient-to-r from-[#080318] to-[rgba(8,3,24,0)] z=0 min-h-screen">
            <Navbar />
            <div className="flex flex-col justify-between min-h-[calc(100vh-78px)]">
              {children}
              <CompanyLogos />
            </div>
          </div>
        </section>
      </body>
    </html>
  );
}
